### ISSUE TITLE
Different responses for different inputs

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [dushanpantic/grpc-server-mock#2]
I haven't found a way to specify different responses for different inputs. Is this currently available?

**Comment by dushanpantic** [comment]
Hey, at the moment that it is not possible.
Currently, we can define an array of responses and have the mock respond in one of two ways, eg:
Response array:
```
[
  {
    "your_message_field_1": "<value1>",
  },
  {
    "your_message_field_1": "<value2>",
  },
  {
    "your_message_field_1": "<value3>",
  },
  ...
]
```
#### 1. Random responses (default behavior)
The mock will pick a random response and return it.

#### 2. Ordered responses (toggled by the `--ordered` flag)
The mock will pick responses in order, so the first call will return response [0], the second call will return response[1], the third call will return response[2], etc. When it runs out of responses, it will start from the response[0] again.
Bear in mind that the `--ordered` flag will make every mocked proto respond in order. I have been planning to make this toggleable on a per-proto basis, by expanding the optional `root.json` file that is placed in the folder with proto file(s).

# ___
Regarding the feature in question, I think it would be a great addition to this lib.
In my opinion, the interface should look like this:
1. Toggled by the `--matched` flag.
2. For `--matched` (and only for it) the array looks like this:
```
[
  {
    "request": {/* request object1 */},
    "response": { /* response object1 */}
  },
  {
    "request": {/* request object2 */},
    "response": { /* response object2 */}
  },
  ...
]
```
3. When an incoming request fully matches the request in the array, the paired response is returned.

Then down the road, a new flag can be added that expects a partial match to return a response.

I have been planning to add support for TLS first, and then refactor [the way response is calculated](https://github.com/dushanpantic/grpc-server-mock/blob/master/src/server/createMockServer.ts#L40-L56) to make it convenient to add new flags. With this feature suggestion/request, I can make the refactor first.

**Comment by mariomurrent-softwaresolutions** [comment]
Fixe with #3

**Comment by dushanpantic** [comment]
Fix is published in the latest package.

**Comment by mariomurrent-softwaresolutions** [comment]
Nice, thank you very much

**Comment by mariomurrent-softwaresolutions** [comment]
@dushanpantic Can you maybe have a look at: https://github.com/meecodebymariomurrent/grpc-server-mock/tree/bug/config-complex-example

I have added an example which does not work if you run the command: grpc-server-mock start:config

Is this an import Issues or can this somehow also fixe in the code?

**Comment by dushanpantic** [comment]
I will take a look later later tonight

**Comment by mariomurrent-softwaresolutions** [comment]
Thx, I think there is no need to reopen this issue - I did not find a place without opening a new Issue to ask to about this topic :)

Also the autogenerate of the config does not work for this example and I don't know why

**Comment by dushanpantic** [comment]
https://github.com/meecodebymariomurrent/grpc-server-mock/blob/cb5979a35b41287aa5f71ee5f4ea4258d9d152ec/examples/config-complex/grpc-server-mock.json#L8
`packageName` should be `config.example`, as that is the package in the [SearchService.proto](https://github.com/meecodebymariomurrent/grpc-server-mock/blob/cb5979a35b41287aa5f71ee5f4ea4258d9d152ec/examples/config-complex/proto/SearchService.proto#L3)

https://github.com/meecodebymariomurrent/grpc-server-mock/blob/cb5979a35b41287aa5f71ee5f4ea4258d9d152ec/examples/config-complex/proto/SearchService.proto#L5
this should be `import "common/searchType.proto";`

`config-complex/google/protobuf/*` can be deleted, it will work without it (I believe its because both protos are "google WellKnown types")

` grpc-server-mock start:config` should work in the `config-complex/` with these changes

**Comment by mariomurrent-softwaresolutions** [comment]
Well the /proto folder is needed for the generation of .ts files. So this is taken from an real example ...
Without the /proto the imports in the .ts files are wrong

**Comment by dushanpantic** [comment]
With the unchanged example, I tried to import the `SearchService.proto` with other software (BloomRPC), and it failed.


After adopting the changes I mentioned above, and switching to the folder structure in the picture below, it worked (both BloomRPC and grpc-server-mock).

![image](https://user-images.githubusercontent.com/11596406/151051977-8447bf27-db18-418d-a49f-b348b711d242.png)

**Comment by mariomurrent-softwaresolutions** [comment]
Hmm, well you are right - maybe we need to adapt the protoc build process
